### ISSUE TITLE
hi 最新版本的代码还在维护吗？

### ISSUE THREAD

**Issue by Huochengyan** [fanpan26/LayIM_NetClient#9]
hi 最新版本的代码还在维护吗？

**Comment by fanpan26** [comment]
@Huochengyan 不好意思已经不再维护了。

**Comment by Huochengyan** [comment]
谢谢，告知



---原始邮件---
发件人: "Fanyuepan"<notifications@github.com&gt;
发送时间: 2020年5月5日(周二) 晚上11:28
收件人: "fanpan26/LayIM.AspNet"<LayIM.AspNet@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"霍城延"<929914120@qq.com&gt;;
主题: Re: [fanpan26/LayIM.AspNet] hi 最新版本的代码还在维护吗？ (#9)




 
@Huochengyan 不好意思已经不再维护了。
